# position-only-ik and orientation-only-ik don't work unless position_only_ik
# is set to true
#
# planning for poses and orientations won't work unless position_only_ik is 
# set to false like when using the interbotix moveit_interface_gui

## KDL

# interbotix_arm:
#   kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
#   position_only_ik: false

## TRAC_IK

# interbotix_arm:
#   kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
#   kinematics_solver_timeout: 0.005
#   solve_type: Speed
#   position_only_ik: false

## LMA

interbotix_arm:
  kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  position_only_ik: false
  kinematics_solver_attempts: 3
