# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

joint1_controller:
  type: effort_controllers/JointPositionController
  joint: joint1
  pid: {p: 600, i: 5.0, d: 30.0, i_clamp: 1}

joint2_controller:
  type: effort_controllers/JointPositionController
  joint: joint2
  pid: {p: 600, i: 5.0, d: 30.0, i_clamp: 1}

joint3_controller:
  type: effort_controllers/JointPositionController
  joint: joint3
  pid: {p: 600, i: 5.0, d: 30.0, i_clamp: 1}

joint4_controller:
  type: effort_controllers/JointPositionController
  joint: joint4
  pid: {p: 450, i: 5.0, d: 10.0, i_clamp: 1}

joint5_controller:
  type: effort_controllers/JointPositionController
  joint: joint5
  pid: {p: 300, i: 5.0, d: 10.0, i_clamp: 1}

joint6_controller:
  type: effort_controllers/JointPositionController
  joint: joint6
  pid: {p: 10, i: 0.0, d: 0}

gripper_controller:
  type: effort_controllers/JointPositionController
  joint: drive_joint
  pid: {p: 50, i: 0.0, d: 0.0}
