arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
    - joint7
  constraints:
    goal_time: 0.5
    stopped_velocity_tolerance: 0.05
    joint1: {trajectory: 1, goal: 0.01}
    joint2: {trajectory: 1, goal: 0.01}
    joint3: {trajectory: 1, goal: 0.01}
    joint4: {trajectory: 1, goal: 0.01}
    joint5: {trajectory: 1, goal: 0.01}
    joint6: {trajectory: 1, goal: 0.01}
    joint7: {trajectory: 1, goal: 0.01}
  stop_trajectory_duration: 0.2
  state_publish_rate:  25
  action_monitor_rate: 10

gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - drive_joint
