controller_list:
  - name: "arm_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints: [waist, shoulder, elbow, wrist_angle]
  - name: "gripper_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints: [left_finger, right_finger]
