controller_names:
  - /wx250s/arm_controller
  - /wx250s/gripper_controller

/wx250s/arm_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - waist
    - shoulder
    - elbow
    - forearm_roll
    - wrist_angle
    - wrist_rotate

/wx250s/gripper_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - left_finger
