# Motor Assist: scale the no-load currents which alleviate the effects of friction
# If the values are invalid, they defaults to 0
motor_assist:
  # Set 'all' to [0, 1] to scale the no load currents of all joints uniformly
  # Or to -1 and use joint specific values
  all: -1
  # Set the joint specific values to [0, 1] to scale differently for each joint
  waist: 0.5
  shoulder: 0.5
  elbow: 0.5
  forearm_roll: 0.5
  wrist_angle: 0.5
  wrist_rotate: 0.5

motor_specs:
  waist:
    # torque constant (Nm/A): how much torque is produced per Amp of current
    torque_constant: 1.793
    # current unit (A): how much current command is needed to produce 1 Amp of current
    current_unit: 0.00269
    # no load current (A): the maximum no load current applied when motor_assist == 1
    # It should be as large as possible without the joint accelerating by itself
    no_load_current: 0.1

  shoulder:
    torque_constant: 1.793
    current_unit: 0.00269
    no_load_current: 0.0

  elbow:
    torque_constant: 1.793
    current_unit: 0.00269
    no_load_current: 0.0

  forearm_roll:
    torque_constant: 0.897
    current_unit: 0.00269
    no_load_current: 0.1

  wrist_angle:
    torque_constant: 0.897
    current_unit: 0.00269
    no_load_current: 0.0

  wrist_rotate:
    torque_constant: 0.897
    current_unit: 0.00269
    no_load_current: 0.1

# Joints specified here but not in motor_assist or motor_specs
# do not support the current control mode
joint_names:
  [waist, shoulder, elbow, forearm_roll, wrist_angle, wrist_rotate, gripper]
